[package]
name = "rust_toolbox"
version = "0.1.0"
description = "A simplekey-value store"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["cargo", "derive"] }


[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
